export const productOptions = {
  Chairs: {
    sizes: ["Standard", "Ergonomic", "Executive", "Stackable"],
    specs: [
      "Fabric Upholstery, Adjustable Height",
      "Leather Upholstery, Lumbar Support",
      "Mesh Back, Swivel Base",
      "Plastic, Foldable",
    ],
  },
  Tables: {
    sizes: [
      "Small (2-4 seats)",
      "Medium (4-6 seats)",
      "Large (6-8 seats)",
      "Conference",
    ],
    specs: [
      "Wooden Top, Metal Frame",
      "Glass Top, Wooden Legs",
      "Foldable, Particle Board",
      "Oval Shape, Veneer Finish",
    ],
  },
  "Sheet Metal": {
    sizes: ["Thin (0.5-1mm)", "Medium (1-3mm)", "Thick (3-5mm)"],
    specs: [
      "Stainless Steel, Polished Finish",
      "Galvanized Steel, Powder Coated",
      "Aluminum, Brushed Finish",
      "Carbon Steel, Matte Finish",
    ],
  },
  Desking: {
    sizes: ["Single Desk", "Double Desk", "Corner Desk", "Workstation"],
    specs: [
      "Laminate Finish, Cable Management",
      "Wooden Top, Metal Frame",
      "Adjustable Height, Ergonomic",
      "Modular, Partition Included",
    ],
  },
  "Solid Wood": {
    sizes: ["Standard", "Custom"],
    specs: [
      "Oak, Natural Finish",
      "Teak, Polished",
      "Pine, Stained",
      "Mahogany, Varnished",
    ],
  },
  Boards: {
    sizes: ["2x3 ft", "3x4 ft", "4x6 ft", "4x8 ft"],
    specs: [
      "Magnetic Whiteboard",
      "Non-Magnetic Whiteboard",
      "Green Chalkboard",
      "Cork Pinboard",
    ],
  },
  "Lab Tables": {
    sizes: ["Small (4x2 ft)", "Medium (6x3 ft)", "Large (8x4 ft)"],
    specs: [
      "Chemical-Resistant Top, Steel Frame",
      "Epoxy Resin Surface, Adjustable Legs",
      "Laminate Top, Storage Drawers",
      "Anti-Slip Surface, Heavy Duty",
    ],
  },
  Others: {
    sizes: ["N/A"],
    specs: [
      "Miscellaneous Furniture Accessories",
      "Decorative Panels",
      "Storage Units",
      "Custom Fixtures",
    ],
  },
};

export const statesAndCities = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Jaganathpuram",
    "Vijayawada",
    "Guntur",
    "Tirupati",
    "Kurnool",
    "Rajahmundry",
    "Nellore",
    "Anantapur",
    "Kadapa",
    "Srikakulam",
    "Eluru",
    "Ongole",
    "Chittoor",
    "Proddatur",
    "Machilipatnam",
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Tawang",
    "Ziro",
    "Pasighat",
    "Bomdila",
    "Naharlagun",
    "Roing",
    "Aalo",
    "Tezu",
    "Changlang",
    "Khonsa",
    "Yingkiong",
    "Daporijo",
    "Seppa",
  ],
  Assam: [
    "Agartala",
    "Tripura",
    "Guwahati",
    "Dibrugarh",
    "Jorhat",
    "Silchar",
    "Tezpur",
    "Tinsukia",
    "Nagaon",
    "Sivasagar",
    "Barpeta",
    "Goalpara",
    "Karimganj",
    "Lakhimpur",
    "Diphu",
    "Golaghat",
    "Kamrup",
  ],
  Bihar: [
    "Patna",
    "Mirzapur",
    "Jehanabad",
    "Mithapur",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Purnia",
    "Ara",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chapra",
    "Sasaram",
    "Hajipur",
    "Bihar Sharif",
    "Sitamarhi",
  ],
  Chhattisgarh: [
    "Raipur",
    "Bilaspur",
    "Durg",
    "Korba",
    "Bhilai",
    "Rajnandgaon",
    "Jagdalpur",
    "Ambikapur",
    "Raigarh",
    "Dhamtari",
    "Kawardha",
    "Mahasamund",
    "Kondagaon",
    "Bijapur",
  ],
  Goa: [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Sanguem",
    "Canacona",
    "Quepem",
    "Valpoi",
    "Sanquelim",
    "Curchorem",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Morbi",
    "Nadiad",
    "Porbandar",
    "Mehsana",
    "Bharuch",
    "Navsari",
    "Surendranagar",
  ],
  Haryana: [
    "Bahadurgarh",
    "Charkhi Dadri",
    "Gurugram",
    "Faridabad",
    "Panipat",
    "Ambala",
    "Hisar",
    "Rohtak",
    "Karnal",
    "Bhiwani",
    "Kaithal",
    "Kurukshetra",
    "Sonipat",
    "Jhajjar",
    "Jind",
    "Fatehabad",
    "Pehowa",
    "Pinjore",
    "Rewari",
    "Yamunanagar",
    "Sirsa",
    "Dabwali",
    "Narwana",
  ],
  "Himachal Pradesh": [
    "Bilaspur",
    "Chamba",
    "Hamirpur",
    "Kangra",
    "Kinnaur",
    "Kullu",
    "Lahaul and Spiti",
    "Mandi",
    "Shimla",
    "Sirmaur",
    "Solan",
    "Una",
  ],
  Jharkhand: [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Chaibasa",
    "Palamu",
    "Gumla",
    "Lohardaga",
    "Dumka",
    "Chatra",
    "Pakur",
    "Jamtara",
    "Simdega",
    "Sahibganj",
    "Godda",
    "Latehar",
    "Khunti",
  ],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Mangaluru",
    "Hubballi",
    "Belagavi",
    "Kalaburagi",
    "Ballari",
    "Davangere",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
    "Vijayapura",
    "Chikkamagaluru",
    "Hassan",
    "Mandya",
    "Raichur",
    "Bidar",
    "Bagalkot",
    "Chitradurga",
    "Kolar",
    "Gadag",
    "Yadgir",
    "Haveri",
    "Dharwad",
    "Ramanagara",
    "Chikkaballapur",
    "Kodagu",
    "Koppal",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Kannur",
    "Alappuzha",
    "Thrissur",
    "Kottayam",
    "Palakkad",
    "Ernakulam",
    "Malappuram",
    "Pathanamthitta",
    "Idukki",
    "Wayanad",
    "Kollam",
    "Kasaragod",
    "Punalur",
    "Varkala",
    "Changanassery",
    "Kayani",
    "Kizhakkambalam",
    "Perumbavoor",
    "Muvattupuzha",
    "Attingal",
    "Vypin",
    "North Paravur",
    "Adoor",
    "Cherthala",
    "Mattancherry",
    "Fort Kochi",
    "Munroe Island",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Gwalior",
    "Jabalpur",
    "Ujjain",
    "Sagar",
    "Ratlam",
    "Satna",
    "Dewas",
    "Murwara (Katni)",
    "Chhindwara",
    "Rewa",
    "Burhanpur",
    "Khandwa",
    "Bhind",
    "Shivpuri",
    "Vidisha",
    "Sehore",
    "Hoshangabad",
    "Itarsi",
    "Neemuch",
    "Chhatarpur",
    "Betul",
    "Mandsaur",
    "Damoh",
    "Singrauli",
    "Guna",
    "Ashok Nagar",
    "Datia",
    "Mhow",
    "Pithampur",
    "Shahdol",
    "Seoni",
    "Mandla",
    "Tikamgarh",
    "Raisen",
    "Narsinghpur",
    "Morena",
    "Barwani",
    "Rajgarh",
    "Khargone",
    "Anuppur",
    "Umaria",
    "Dindori",
    "Sheopur",
    "Alirajpur",
    "Jhabua",
    "Sidhi",
    "Harda",
    "Balaghat",
    "Agar Malwa",
  ],
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Kolhapur",
    "Thane",
    "Satara",
    "Latur",
    "Chandrapur",
    "Jalgaon",
    "Bhiwandi",
    "Shirdi",
    "Akola",
    "Parbhani",
    "Raigad",
    "Washim",
    "Buldhana",
    "Nanded",
    "Yavatmal",
    "Beed",
    "Amravati",
    "Kalyan",
    "Dombivli",
    "Ulhasnagar",
    "Nagothane",
    "Vasai",
    "Virar",
    "Mira-Bhayandar",
    "Dhule",
    "Sangli",
    "Wardha",
    "Ahmednagar",
    "Pandharpur",
    "Malegaon",
    "Osmanabad",
    "Gondia",
    "Baramati",
    "Jalna",
    "Hingoli",
    "Sindhudurg",
    "Ratnagiri",
    "Palghar",
    "Ambarnath",
    "Badlapur",
    "Taloja",
    "Alibaug",
    "Murbad",
    "Karjat",
    "Pen",
    "Newasa",
  ],
  Manipur: [
    "Imphal",
    "Churachandpur",
    "Thoubal",
    "Bishnupur",
    "Kakching",
    "Senapati",
    "Ukhrul",
    "Tamenglong",
    "Jiribam",
    "Moreh",
    "Noney",
    "Pherzawl",
    "Kangpokpi",
  ],
  Meghalaya: [
    "Shillong",
    "Tura",
    "Nongpoh",
    "Cherrapunjee",
    "Jowai",
    "Baghmara",
    "Williamnagar",
    "Mawkyrwat",
    "Resubelpara",
    "Mairang",
  ],
  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Serchhip",
    "Kolasib",
    "Saiha",
    "Lawngtlai",
    "Mamit",
    "Hnahthial",
    "Khawzawl",
    "Saitual",
  ],
  Nagaland: [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Mon",
    "Zunheboto",
    "Phek",
    "Longleng",
    "Kiphire",
    "Peren",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Puri",
    "Sambalpur",
    "Berhampur",
    "Balasore",
    "Baripada",
    "Bhadrak",
    "Jeypore",
    "Angul",
    "Dhenkanal",
    "Keonjhar",
    "Kendrapara",
    "Jagatsinghpur",
    "Paradeep",
    "Bargarh",
    "Rayagada",
    "Koraput",
    "Nabarangpur",
    "Kalahandi",
    "Nuapada",
    "Phulbani",
    "Balangir",
    "Sundargarh",
  ],
  Punjab: [
    "Amritsar",
    "Bathinda",
    "Barnala",
    "Faridkot",
    "Fatehgarh Sahib",
    "Fazilka",
    "Ferozepur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Kapurthala",
    "Ludhiana",
    "Malerkotla",
    "Mansa",
    "Moga",
    "Pathankot",
    "Patiala",
    "Rupnagar",
    "S.A.S. Nagar", // Sahibzada Ajit Singh Nagar
    "Sangrur",
    "Shaheed Bhagat Singh Nagar", // Nawanshahr
    "Sri Muktsar Sahib",
    "Tarn Taran",
  ],
  Rajasthan: [
    "Baran",
    "Newai",
    "Gaganagar",
    "Suratgarh",
    "Jaipur",
    "Udaipur",
    "Jodhpur",
    "Kota",
    "Ajmer",
    "Bikaner",
    "Alwar",
    "Bharatpur",
    "Sikar",
    "Pali",
    "Nagaur",
    "Jhunjhunu",
    "Chittorgarh",
    "Tonk",
    "Barmer",
    "Jaisalmer",
    "Dholpur",
    "Bhilwara",
    "Hanumangarh",
    "Sawai Madhopur",
  ],
  Sikkim: [
    "Gangtok",
    "Namchi",
    "Pelling",
    "Geyzing",
    "Mangan",
    "Rangpo",
    "Jorethang",
    "Yuksom",
    "Ravangla",
    "Lachen",
    "Lachung",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Erode",
    "Tirunelveli",
    "Vellore",
    "Thanjavur",
    "Tuticorin",
    "Dindigul",
    "Cuddalore",
    "Kancheepuram",
    "Nagercoil",
    "Kumbakonam",
    "Karur",
    "Sivakasi",
    "Namakkal",
    "Tiruppur",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Mahbubnagar",
    "Ramagundam",
    "Siddipet",
    "Adilabad",
    "Nalgonda",
    "Mancherial",
    "Kothagudem",
    "Zaheerabad",
    "Miryalaguda",
    "Bhongir",
    "Jagtial",
  ],
  Tripura: [
    "Agartala",
    "Udaipur",
    "Dharmanagar",
    "Kailashahar",
    "Belonia",
    "Kamalpur",
    "Ambassa",
    "Khowai",
    "Sabroom",
    "Sonamura",
    "Melaghar",
  ],
  "Uttar Pradesh": [
    "Shikohabad",
    "Baghpat",
    "Mahuwadabar",
    "Anandnagar Maharajganj",
    "Badhnan",
    "Khalilabad",
    "Lucknow",
    "Matbarganj",
    "Kasganj",
    "Kanpur",
    "Varanasi",
    "Agra",
    "Prayagraj (Allahabad)",
    "Ghaziabad",
    "Noida",
    "Meerut",
    "Aligarh",
    "Bareilly",
    "Moradabad",
    "Saharanpur",
    "Gorakhpur",
    "Firozabad",
    "Jhansi",
    "Muzaffarnagar",
    "Mathura-Vrindavan",
    "Budaun",
    "Rampur",
    "Shahjahanpur",
    "Farrukhabad-Fatehgarh",
    "Ayodhya",
    "Unnao",
    "Jaunpur",
    "Lakhimpur",
    "Hathras",
    "Banda",
    "Pilibhit",
    "Barabanki",
    "Khurja",
    "Gonda",
    "Mainpuri",
    "Lalitpur",
    "Sitapur",
    "Etah",
    "Deoria",
    "Ghazipur",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Rishikesh",
    "Mussoorie",
    "Almora",
    "Pithoragarh",
    "Haldwani",
    "Rudrapur",
    "Bageshwar",
    "Champawat",
    "Uttarkashi",
    "Roorkee",
    "Tehri",
    "Lansdowne",
  ],
  "West Bengal": [
    "Kolkata",
    "Garia",
    "Darjeeling",
    "Siliguri",
    "Howrah",
    "Asansol",
    "Durgapur",
    "Malda",
    "Cooch Behar",
    "Haldia",
    "Kharagpur",
    "Raiganj",
    "Bardhaman",
    "Jalpaiguri",
    "Chandannagar",
    "Kalimpong",
    "Alipurduar",
  ],
  "Andaman and Nicobar Islands": [
    "Port Blair",
    "Havelock Island",
    "Diglipur",
    "Neil Island",
    "Car Nicobar",
    "Little Andaman",
    "Long Island",
    "Mayabunder",
    "Campbell Bay",
    "Rangat",
    "Wandoor",
  ],
  Chandigarh: [
    "Sector 1",
    "Sector 2",
    "Sector 3",
    "Sector 4",
    "Sector 5",
    "Sector 6",
    "Sector 7",
    "Sector 8",
    "Sector 9",
    "Sector 10",
    "Sector 11",
    "Sector 12",
    "Sector 14",
    "Sector 15",
    "Sector 16",
    "Sector 17",
    "Sector 18",
    "Sector 19",
    "Sector 20",
    "Sector 21",
    "Sector 22",
    "Sector 23",
    "Sector 24",
    "Sector 25",
    "Sector 26",
    "Sector 27",
    "Sector 28",
    "Sector 29",
    "Sector 30",
    "Sector 31",
    "Sector 32",
    "Sector 33",
    "Sector 34",
    "Sector 35",
    "Sector 36",
    "Sector 37",
    "Sector 38",
    "Sector 39",
    "Sector 40",
    "Sector 41",
    "Sector 42",
    "Sector 43",
    "Sector 44",
    "Sector 45",
    "Sector 46",
    "Sector 47",
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Daman",
    "Diu",
    "Silvassa",
    "Amli",
    "Kachigam",
    "Naroli",
    "Vapi",
    "Marwad",
    "Samarvarni",
    "Kawant",
  ],
  Delhi: [
    "New Delhi",
    "Rani Bagh",
    "Shalimar Bagh",
    "Tilak Nagar",
    "Hari Nagar Dadb",
    "Hari Nagar",
    "Maya Puri",
    "Alaknanda",
    "Old Delhi",
    "Dwarka",
    "Rohini",
    "Karol Bagh",
    "Lajpat Nagar",
    "Saket",
    "Vasant Kunj",
    "Janakpuri",
    "Mayur Vihar",
    "Shahdara",
    "Preet Vihar",
    "Pitampura",
    "Chanakyapuri",
    "Narela",
    "Mehrauli",
    "Najafgarh",
    "Okhla",
    "Tilak Nagar",
  ],
  "Jammu and Kashmir": [
    "Anantnag",
    "Bandipora",
    "Baramulla",
    "Budgam",
    "Doda",
    "Ganderbal",
    "Jammu",
    "Kathua",
    "Kishtwar",
    "Kulgam",
    "Kupwara",
    "Poonch",
    "Pulwama",
    "Rajouri",
    "Ramban",
    "Reasi",
    "Samba",
    "Shopian",
    "Srinagar",
    "Udhampur",
  ],
  Ladakh: [
    "Leh",
    "Kargil",
    "Diskit",
    "Padum",
    "Nubra",
    "Tangtse",
    "Sankoo",
    "Zanskar",
    "Nyoma",
    "Turtuk",
    "Hanle",
  ],
  Lakshadweep: [
    "Kavaratti",
    "Agatti",
    "Minicoy",
    "Amini",
    "Andrott",
    "Kalpeni",
    "Kadmat",
    "Chetlat",
    "Bitra",
    "Bangaram",
  ],
  Puducherry: [
    "Puducherry",
    "Karaikal",
    "Mahe",
    "Yanam",
    "Villianur",
    "Bahour",
    "Oulgaret",
    "Ariyankuppam",
    "Nettapakkam",
  ],
};

export const orderTypeOptions = [
  "B2G",
  "B2C",
  "B2B",
  "Demo",
  "Replacement",
  "Stock Out",
];
export const companyOptions = ["Promark", "Foxmate", "Promine", "Primus"];

export const paymentMethodOptions = ["Cash", "NEFT", "RTGS", "Cheque"];
export const paymentTermsOptions = [
  "100% Advance",
  "Partial Advance",
  "Credit",
];
export const salesPersonlist = [
  "Aasim Musadiq",
  "Abhay Pratap Singh",
  "Abhay Bhardwaj",
  "Abhayjit Sekhon",
  "Ajay Kumar",
  "Amarjeet Singh",
  "Aniket Singh",
  "Anil Kumar",
  "Animesh Trivedi",
  "Anirban Syam",
  "Ankit Sharma",
  "Anup Panday",
  "Arif Khan",
  "Arwinder Singh",
  "Ashwani Kumar",
  "Awadesh Kumar Srivastav",
  "Bachan Pal",
  "Barjesh Singh",
  "Ekant Yati",
  "Gursewak Singh",
  "Harish Kumar",
  "Heera Singh Daspa",
  "Harpeet Singh",
  "J P Sharma",
  "Jagan Lal",
  "Javvad Akram",
  "Kulwinder Singh",
  "Manish CS Lange",
  "Manjit Singh Chowhan",
  "Mayank Goutam",
  "Mayank Prasad",
  "Nikhil Sharma",
  "Parmjeet Singh",
  "Pitamber Sharma",
  "Priya Sharma",
  "PS Brar",
  "Purnendu Kumar",
  "Raj Bahadur Singh",
  "Rajeev Kanda",
  "Rajeev Kumar Singh",
  "Rajeev Pal Singh",
  "Rajesh Kumar",
  "Rakesh Kumar",
  "Ramkumar Singh",
  "Ranbeer Kaur",
  "Rachit Arya",
  "Rohit Kumar Tiwari",
  "Sahil Gupta",
  "Sahil Kapoor",
  "Sahiba",
  "Savir Khan",
  "Shri Kant",
  "Siddhartha Kumar",
  "Sidhant Oberai",
  "Sidhant Prajapati",
  "Sukhjinder Pal Singh",
  "Sumit Kushwaha",
  "Sunil Kukkar",
  "Surbhi Chugh",
  "Sushil Kumar",
  "Vageesh Bhardwaj",
  "Vaibhav Mishra",
  "Varun Budhiraja",
  "Vaseem Khan",
];

export const Reportinglist = [
  "Abhay Pratap Singh",
  "Abhayjit Sekhon",
  "Amarjeet Singh",
  "Arwinder Singh",
  "Ashwani Kumar",
  "Bachan Pal",
  "Harpeet Singh",
  "Harsimran",
  "J P Sharma",
  "Manish CS Lange",
  "Manjit Singh Chowhan",
  "Mayank Prasad",
  "Nikhil Sharma",
  "PS Brar",
  "Priya Sharma",
  "Purnendu Kumar",
  "Raj Bahadur Singh",
  "Rajeev Kanda",
  "Rajeev Kumar Singh",
  "Rajeev Pal Singh",
  "Sahil Gupta",
  "Sahil Kapoor",
  "Savir Khan",
  "Siddhartha Kumar",
  "Sukhjinder Pal Singh",
  "Sumit Kushwaha",
  "Sunil Kukkar",
  "Surbhi Chugh",
  "Sushil Kumar",
  "Varun Budhiraja",
  "Vaseem Khan",
];

export const modelNoOptions = ["AT"];
export const brandOptions = ["Promark", "White Label"];
export const dispatchFromOptions = [
  "Patna",
  "Bareilly",
  "Ranchi",
  "Morinda",
  "Lucknow",
  "Delhi",
  "Jaipur",
  "Rajasthan",
];
